#spring:
#  application:
#    name: order-service
    
#server:
#  port: 8201
  
#eureka:
#  client:
#    service-url:
#      #结合云服务才能设置其他选项
#      #服务提供者应该向所有的eureka服务器发送地址，这样可以避免一台eureka宕机，服务提供者还能向其他的eureka发送地址
#      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka


spring:
  application:
    name: order-service
    
# server:
#  port: 8201
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202

